# Generated by Django 5.0.1 on 2024-02-22 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='type_choices',
            new_name='type',
        ),
    ]
