# Generated by Django 5.0.1 on 2024-04-16 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_region_category_slug_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('yangi', 'Yangi'), ('yetkazildi', 'Yetkazildi'), ('arxivlandi', 'Arxivlandi'), ('yetkazilmoqda', 'Yetkazilmoqda'), ('nosoz_mahsulot', 'Nosoz_maxsulot'), ('qaytib_keldi', 'Qaytib_keldi'), ('bekor_qilindi', 'Bekor_qilibdi'), ('keyin_oladi', 'Keyin_oladi'), ('dastavkaga_tayyor', 'Dastavkaga_tayyor')], default='yangi', max_length=30),
        ),
    ]
