# Generated by Django 5.0.1 on 2024-02-27 12:57

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_product_created_at_product_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default='users/images/default.png', force_format='JPEG', keep_meta=True, null=True, quality=75, scale=0.5, size=[168, 168], upload_to='category/images'),
        ),
    ]
