# Generated by Django 5.0.1 on 2024-04-26 13:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('apps', '0009_order_created_at_order_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(
                choices=[('yangi', 'Yangi'), ('yetkazildi', 'Yetkazildi'), ('arxivlandi', 'Arxivlandi'),
                         ('yetkazilmoqda', 'Yetkazilmoqda'), ('nosoz_mahsulot', 'Nosoz_maxsulot'),
                         ('qaytib_keldi', 'Qaytib_keldi'), ('bekor_qilindi', 'Bekor qilibdi'),
                         ('keyin_oladi', 'Keyin oladi'), ('dastavkaga_tayyor', 'Dastavkaga_tayyor')], default='yangi',
                max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(editable=False, max_length=255, unique=True),
        ),
    ]
