# Generated by Django 5.0.1 on 2024-05-15 13:29

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0012_alter_district_options_alter_region_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('yangi', 'Yangi'), ('yetkazildi', 'Yetkazildi'), ('arxivlandi', 'Arxivlandi'), ('yetkazilmoqda', 'Yetkazilmoqda'), ('nosoz_mahsulot', 'Nosoz maxsulot'), ('qaytib_keldi', 'Qaytib keldi'), ('bekor_qilindi', 'Bekor qilindi'), ('keyin_oladi', 'Keyin oladi'), ('dastavkaga_tayyor', 'Dastavkaga tayyor'), ('hold', 'Hold')], default='yangi', max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
        ),
    ]
